import { Lato } from "next/font/google";
import "@/styles/globals.css";

import { SecondaryHeader } from "@/components/Header";

const latoSans = Lato({
  weight: ["100", "300", "400", "700", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Configurações",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={`${latoSans.weight}`}>
        <SecondaryHeader />
        {children}
      </body>
    </html>
  );
}
