import { Lato } from "next/font/google";
import "@/styles/globals.css";
import { MainHeader } from "@/components/Header";

const latoSans = Lato({
  weight: ["100", "300", "400", "700", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Bora ficar giga?",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={`${latoSans.weight}`}>
        <MainHeader />
        {children}
      </body>
    </html>
  );
}
